name: Ruby

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Bundler
      run: gem install bundler
    - name: Install Bundle
      run: |
        cd SampleApp 
        bundle install --jobs 4 --retry 3
    - name: Execute Unlimit
      run: |
        cd SampleApp
        bundle exec unlimit 2>&1 | tee output.txt
        cat output.txt
        if grep -q "No valid codesigning identities found on your Mac" output.txt; then echo "Success"; else exit 1; fi
